markdown: rdiscount
pygments: true

# Template Settings
title: 'Apps and the City Berlin'
location:
- text: 'Supermarkt Berlin'
  url: 'http://www.supermarkt-berlin.net/'
date: '29. November 2012'
github: 'https://github.com/okfde/berlin.appsandthecity'
contact: 'julia.kloiber@okfn.org'
mailinglist: 'http://lists.okfn.org/mailman/listinfo/open-data-nahverkehr'

# Navigation
navigation:
- text: 'Beispiele'
  url: '/#beispiele'
- text: 'Entwicklertag'
  url: '/#entwicklertag'
- text: 'Argumente'
  url: '/#argumente'
- text: 'Daten'
  url: '/daten'
- text: 'Apps'
  url: '/apps'
- text: 'Media'
  url: '/media'
